### ISSUE TITLE
Please fix a bug as soon as possible

### ISSUE THREAD

**Issue by Shinetaku** [eraydin/EPPlus.Core.Extensions#15]
bug :Object reference not set to an instance of an object.
in src/EPPlus.Core.Extensions/ExcelTableExtensions.cs 185

fixed:
-- col = table.Columns[propertyInfo.Name].Position;
+col = table.Columns.FirstOrDefault(x => x.Name.Equals(propertyInfo.Name)).Position;

**Comment by Shinetaku** [comment]
In **EPPlus**

    /// <summary>Indexer</summary>
    /// <param name="Name">**The name of the table**</param>
    /// <returns>**The table column. Null if the table name is not found in the collection**</returns>
    public ExcelTableColumn this[string Name] { get; }

**Comment by eraydin** [comment]
Thank you @Shinetaku for your feedback. I will investigate and fix this null pointer shit as soon as possible.

**Comment by eraydin** [comment]
Closed with #d694e4f76f13c5288c1a078dd370176d41bdf4fc

**Comment by Shinetaku** [comment]
Bug is still going on

ERROR 2018-07-01 20:58:52,336 [6    ] Mvc.ExceptionHandling.AbpExceptionFilter - '' column could not found on the worksheet.
EPPlus.Core.Extensions.Exceptions.ExcelValidationException: '' column could not found on the worksheet.
   at EPPlus.Core.Extensions.ExcelTableExtensions.<PrepareMappings>d__5`1.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EPPlus.Core.Extensions.ExcelTableExtensions.<AsEnumerable>d__2`1.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

**Comment by Shinetaku** [comment]
please fixed it as I described above, test through

col = table.Columns.FirstOrDefault(x => x.Name.Equals(propertyInfo.Name)).Position;
