### ISSUE TITLE
Bug is still going on

### ISSUE THREAD

**Issue by Shinetaku** [eraydin/EPPlus.Core.Extensions#16]
Bug is still going on

ERROR 2018-07-01 20:58:52,336 [6 ] Mvc.ExceptionHandling.AbpExceptionFilter - '' column could not found on the worksheet.
EPPlus.Core.Extensions.Exceptions.ExcelValidationException: '' column could not found on the worksheet.
at EPPlus.Core.Extensions.ExcelTableExtensions.d__51.MoveNext() at System.Collections.Generic.List1.AddEnumerable(IEnumerable1 enumerable) at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source)
at EPPlus.Core.Extensions.ExcelTableExtensions.d__21.MoveNext() at System.Collections.Generic.List1.AddEnumerable(IEnumerable1 enumerable) at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source)

**Comment by Shinetaku** [comment]
please fixed it as I described previously, test through

col = table.Columns.FirstOrDefault(x => x.Name.Equals(propertyInfo.Name)).Position;

**Comment by eraydin** [comment]
@Shinetaku could you please send me your Excel file? I will test it through your file.

**Comment by eraydin** [comment]
as your code as well

**Comment by Shinetaku** [comment]
![111](https://user-images.githubusercontent.com/17084061/42166022-57d31462-7e3c-11e8-917d-de4fb872049f.png)

**Comment by Shinetaku** [comment]
![222](https://user-images.githubusercontent.com/17084061/42166142-ab1c1056-7e3c-11e8-8a25-d04c5c69e544.png)

**Comment by Shinetaku** [comment]
Error in :
var editDtoList = worksheet.ToList<TEditDto>();

Because of localization, excel column title with [xxxx].

**Comment by eraydin** [comment]
@Shinetaku, does your TEditDto has ExcelTableColumn attributes on its properties? It looks like your ExcelTableColumn attributes do not match with worksheet columns.

On the other hand, if you have a localization problem, so you can map properties using column index. 

For example:
```
public class TEditDto
    {      
        [ExcelTableColumn(1)]       
        public string UserCode { get; set; } 

        [ExcelTableColumn(2)]       
        public string UserName { get; set; }   		
    }  	
	
	
var results = excelPackage.GetWorksheet(1).ToList<TEditDto>(cfg => cfg.SkipCastingErrors()); // Also, you can skip casting errors to not throw any exception.
	
```    	
	
Actually, I did not understand your problem quite well. If you do not find my answer satisfactory, please have a detailed look at the test project and *README.md* file. 

Additionally, this project is open for contribution. So, you can fix the problem, and send a PR.

**Comment by Shinetaku** [comment]
thanks,i try set ExcelTableColumn index, its ok.
