### ISSUE TITLE
Custom converter when parsing workbook

### ISSUE THREAD

**Issue by Liero** [eraydin/EPPlus.Core.Extensions#18]
I have existing excel, with column with values 0 or 1 (general data type).

Is it possible to map it to Boolean?

**Comment by eraydin** [comment]
Hello @Liero,

Currently, it is not possible, but it will be supported by the next release. https://github.com/eraydin/EPPlus.Core.Extensions/commit/50ed38af0c8b7bdbe34b15d110f75f5c40a455de

Thank you.

**Comment by eraydin** [comment]
Released https://www.nuget.org/packages/EPPlus.Core.Extensions/2.3.0
