### ISSUE TITLE
Missing column name in exception message

### ISSUE THREAD

**Issue by Liero** [eraydin/EPPlus.Core.Extensions#19]
**GIVEN** that I use `ExcelTableColumAttribute` without explicitly specifying the column name:

        [ExcelTableColumn]
        public string MyColumn { get; set; }

**WHEN** the column is missing in excel

**THEN** then `.ToList<MyClass>()` throws exception, but the exception message does not contain the column name. It just shows empty quotes

**Comment by eraydin** [comment]
Hello Liero,

Thank you again for your feedback. The problem has been fixed with #F745b9cd7ff147f9ab7a9d8073af8bf8cebbe9c7a , and It will be released with the next version.

Have a good day.

**Comment by eraydin** [comment]
Released https://www.nuget.org/packages/EPPlus.Core.Extensions/2.3.1
