### ISSUE TITLE
AsExcelTable() doesn't work as expected when .NET property order doesn't match Excel columns

### ISSUE THREAD

**Issue by ahardin** [eraydin/EPPlus.Core.Extensions#2]
My scenario is as follows:

- Worksheet does not have a Table, but does have a header row
- Using ExcelTableColumnAttributes with ColumnNames specified
- I have some properties on the POCO that should not map to an Excel column

The behavior that I expected was that the ColumnNames in the ExcelTableColumnAttributes would simply tell EPPlus which properties map to which columns.

But, since AsExcelTable() uses the indexes of the PropertyInfo array as the index accessor of the Columns array, it's effectively setting the Table column names based on the order of T's properties. These 1.) leads to properties being improperly mapped, and 2.) doesn't allow for non-mapped properties.

I was messing around with something similar to the following, but I don't think it's quite right. I guess I'm a little confused, because I don't see a scenario in which I would want the current behavior of that loop through `propInfo[]`.

```csharp
            if (useExcelColumnNames)
            {
                for (int col = 1; col <= worksheet.Dimension.End.Column; col++)
                {
                    var headerValue = worksheet.Cells[1, col].Value.ToString();
                    worksheet.Tables[tableName].Columns[col - worksheet.Dimension.Start.Column].Name = headerValue.Trim();
                }

                return worksheet.Tables[tableName];
            }
```

I'm happy to iterate on this with you to come up with a good solution. I'm actively using EPPlus and your extensions in a project.

**Comment by eraydin** [comment]
Hello,

Yes, you are right. Actually, there is no need to use the POCO object in AsExcelTable() method. So, I removed these junk codes from there (with https://github.com/eraydin/EPPlus.Core.Extensions/commit/923de106e92a863072362a5962ebcb018a5bcc70). The problem will be fixed in the next release.

Thank you for your contribution.
