### ISSUE TITLE
How to set CultureInfo when parsing excel

### ISSUE THREAD

**Issue by Liero** [eraydin/EPPlus.Core.Extensions#20]
How do I explicitely set CultureInfo when parsing DateTime like in following example?

    public class MyClass
    {
        [ExcelTableColumn]
        public DateTime DateColumn { get; set; }
    }

    var items = sheets1.ToList<MyClass>();

**Comment by eraydin** [comment]
Hello Liero,

Currently, it does not has any localisation related feature, but you can intercept parsing operation and set 'CultureInfo' like the example below.

` var items = sheets1.ToList<MyClass>(cfg => cfg.Intercept((curr, index) =>
            {
                curr.DateColumn = DateTime.Parse(curr.DateColumn.ToShortDateString(), CultureInfo.CreateSpecificCulture("tr-TR"));
            }));`

Thank you for the feedback. I will consider this idea for future releases.

**Comment by Liero** [comment]
It is extremely important, because excel does use localized date formats

**Comment by eraydin** [comment]
@Liero what do you think about contributing to this project by developing the feature you mentioned?

**Comment by Liero** [comment]
I will look at it this week, since it is critical for my project. Could you give me some quick tips, where in the code to look first? Also, if you left the issue open, somebody could pick it...
