### ISSUE TITLE
Bug: Cannot parse workseet created by collection.ToExcelPackage();

### ISSUE THREAD

**Issue by Liero** [eraydin/EPPlus.Core.Extensions#23]
public class BugRepo
    {
        [Fact]
        public void Worksheet_CreatedBy_ToExcelPackage_ShouldBeParseable()
        {
            var rows = new[]
            {
                new DtoString(){ DateColumn = new DateTime(2019,12,30).ToString() }
            };
            var excelPackage = rows.ToExcelPackage();
            var worksheet = excelPackage.Workbook.Worksheets["DtoString"];

            //throws EPPlus.Core.Extensions.Exceptions.ExcelValidationException : 'DateColumn' column could not found on the worksheet.
            var parsedRows = worksheet.ToList<DtoString>();      
        }

        public class DtoString
        {
            [ExcelTableColumn]
            public string DateColumn { get; set; }
        }
    }

I've cloned Dev branch: https://github.com/eraydin/EPPlus.Core.Extensions/tree/534b6f20a418587eed3f6e64e12b849aa6479255

The problem is that .ToExcelPackage() generated excel table with column Column1, although header is correct

**Comment by eraydin** [comment]
Hello @Liero,

Thank you for reporting this bug. I will investigate, and fix it.

Have a nice day.

**Comment by eraydin** [comment]
Hello again @Liero,

Can you update your _ExcelTableColumn_ attribute as '_[ExcelTableColumn(1)]_' or '_[ExcelTableColumn("DateColumn")]_'. After that the problem should be fixed.

**Comment by Liero** [comment]
`[ExcelTableColumn("DateColumn")]` throws the same error and `[ExcelTableColumn(1)]` is not relevant.


Anyway, even if both worked, it is still a bug

**Comment by eraydin** [comment]
I am aware of this problem. It is already fixed, and will be released with the next version.

**Comment by eraydin** [comment]
Released https://www.nuget.org/packages/EPPlus.Core.Extensions/2.3.2
