### ISSUE TITLE
Optional Columns

### ISSUE THREAD

**Issue by schneiderpat** [eraydin/EPPlus.Core.Extensions#24]
Hey :)

Is there a way to set a column to optional when parsing a sheet?
The following throws an error if the column is not present.
``` csharp
   [ExcelTableColumn("First name")]
   public string FirstName { get; set; }
```

**Comment by eraydin** [comment]
Hello @schneiderpat,

Currently, it does not support optional column mappings, but this is such a nice idea. Thank you for the feedback. I am adding it to the road map, and this feature most likely will be released with the next version.  I will inform you via this thread once it is released.

Have a nice day.

**Comment by eraydin** [comment]
Released with https://www.nuget.org/packages/EPPlus.Core.Extensions/2.4.0
