### ISSUE TITLE
ToList behaviour

### ISSUE THREAD

**Issue by osoykan** [eraydin/EPPlus.Core.Extensions#8]
How about if we enrich the `ToList<>` as behavioral. For example; 

```csharp
excelPackage.Workbook.Worksheets.First().ToList<CandidateProduct>(@candidateProduct => {
   @candidateProduct.Barcode = @candidateProduct.Barcode.Trim();
   @candidateProduct.LocalizedString = L(@candidateProduct.LocalizedKey);
});
```

If we can use a delegate to intercept ToList action along with converted item that would be fine.

**Comment by osoykan** [comment]
Implemented with https://github.com/osoykan/EPPlus.Core.Extensions/commit/afdb8eec42e6aa4596a4bee148908357ab5a87a4

**Comment by eraydin** [comment]
Thank you so much @osoykan for your contribution.
